# Generated by Django 2.0.5 on 2018-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_auto_20180820_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirm',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
