# Generated by Django 2.1 on 2018-10-01 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0003_auto_20181001_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='contact_name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transandreview',
            name='contact_phone',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transandreview',
            name='ratings',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
