# Generated by Django 2.1 on 2018-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0004_auto_20181001_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='end_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transandreview',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
