# Generated by Django 2.1 on 2018-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0005_auto_20181001_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='comment_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transandreview',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transandreview',
            name='start_time',
            field=models.DateField(),
        ),
    ]
