# Generated by Django 2.1 on 2018-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0006_auto_20181001_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='status',
            field=models.CharField(choices=[('B', 'Booking'), ('C', 'Comfirming'), ('S', 'Success')], default='B', max_length=20),
        ),
    ]
