# Generated by Django 2.1 on 2018-10-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendingAndBooking', '0007_auto_20181001_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transandreview',
            name='comment_content',
            field=models.CharField(default='Very good!', max_length=500),
        ),
    ]
