# Generated by Django 2.0.5 on 2018-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acommodation', '0002_auto_20180819_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
