# Generated by Django 2.0.5 on 2018-08-25 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('types_property', models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('S', 'Studio'), ('O', 'others')], default='O', max_length=1)),
                ('num_guests', models.IntegerField(default=0)),
                ('num_rooms', models.IntegerField(default=0)),
                ('num_doubleBed', models.IntegerField(default=0)),
                ('num_singleBed', models.IntegerField(default=0)),
                ('num_sofaBed', models.IntegerField(default=0)),
                ('num_bathrooms', models.IntegerField(default=0)),
                ('overall_size', models.FloatField(default=0.0)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_toiletries', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('has_dryer', models.BooleanField(default=False)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_hair_dryer', models.BooleanField(default=False)),
                ('has_TV', models.BooleanField(default=False)),
                ('has_crib', models.BooleanField(default=False)),
                ('has_bathtub', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_gyms', models.BooleanField(default=False)),
                ('has_swimming_pools', models.BooleanField(default=False)),
                ('is_allowed_party', models.BooleanField(default=False)),
                ('is_allowed_pet', models.BooleanField(default=False)),
                ('is_allowed_smoking', models.BooleanField(default=False)),
                ('is_allowed_couple', models.BooleanField(default=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=3)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user_description', models.TextField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
