# Generated by Django 2.1 on 2018-08-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_auto_20180826_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Property.pid+', to='Property.Property'),
        ),
    ]
